### ISSUE TITLE
Structure of this pkg

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3featsel#1]
Should/could follow _mlr3tuning_ [structure](https://github.com/mlr-org/mlr3tuning/blob/master/R/Tuner.R).

- Two base classes (`Filter` and `Featsel`) or one class with respective functions?

Arguments: 
- `id` 
- `settings` (at least for `Filter`)
- `result` -> returns the full `Filter Values` (needed for eventual caching) and the subsetted task in case of `Featsel`
- [...] more?

For filters a subclass per pkg that inherits from the main class? 
How should we do the structuring for featsel methods?

@ja-thomas

**Comment by ja-thomas** [comment]
Sounds good, for now, let's start with a minimal amount of arguments.

def. inheritance from a base class imo.

For Featsel we can I think directly use something very similar to `Tuner.R` except that we return the selected feature names instead of par.vals. 
I would assume we also have an OptPath but I can't really see where it is used in mlr3tuning.

**Comment by pat-s** [comment]
> For Featsel: I guess we also want something like ignore.feats or forced.feats, i.e., features that are always included.

We should put requests like these into separate issues. Closing here since the structure of the pkg is now quite clear.
