### ISSUE TITLE
Initialization methods of filters have unused arguments

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3featsel#5]
E.g., `FilterAUC` has:
```r
initialize = function(id, packages,
      feature_types,
      task_type,
      settings = list(na.rm = TRUE)) {
      super$initialize(
        id = "FilterAUC",
        packages = "stats",
        feature_types = "numeric",
        task_type = "classif",
        settings = settings)
    }
```
Only settings is used, the other arguments are silently ignored. 

I'd suggest this:
```r
initialize = function(id = "FilterAUC", settings = list(na.rm = TRUE)) {
      super$initialize(
        id = assert_string(id),
        packages = "stats",
        feature_types = "numeric",
        task_type = "classif",
        settings = assert_list(settings, names = "unique"))
    }
```

**Comment by mllg** [comment]
We also need to discuss if the settings are hyperparameters and if yes, we want to have a ParamSet for them in order to be able to tune them.

**Comment by ja-thomas** [comment]
Do filter often have settings? If there are only a very few parameters I think having them as parsets might be overkill.

Tuning can still be realized via pipelines.

**Comment by mllg** [comment]
> Tuning can still be realized via pipelines.

If we don't have a way to ask the filter which hyperparameters are available, this will be difficult.

**Comment by pat-s** [comment]
In https://github.com/mlr-org/mlr3featsel/commit/9db45fe5fba20be09723789822d17a35d59cbd6f I've removed the unnecessary constructor objects.

I haven't used `id = assert_string(id),` as these assertions checks are done in the constructor of the parent class and would be initialized twice otherwise.

> Do filter often have settings? If there are only a very few parameters I think having them as parsets might be overkill.
> 
> Tuning can still be realized via pipelines.

I also think so. First make the filters itself tuneable (to be able to use ensemble filters) and stay with the current implementation.
